### ISSUE TITLE
unable to build sassc

### ISSUE THREAD

**Issue by ligio90** [sass/sassc#246]
When I try to install sassc on my Ubuntu computer (using `gem install sassc -v '2.0.0'`), it is unable to build. How can I fix it, thanks.

`Building native extensions. This could take a while...
ERROR:  Error installing sassc:
	ERROR: Failed to build gem native extension.

    current directory: /var/lib/gems/2.5.0/gems/sassc-2.0.0/ext
/usr/bin/ruby2.5 -rrubygems /var/lib/gems/2.5.0/gems/rake-12.3.2/exe/rake RUBYARCHDIR=/var/lib/gems/2.5.0/extensions/x86_64-linux/2.5.0/sassc-2.0.0 RUBYLIBDIR=/var/lib/gems/2.5.0/extensions/x86_64-linux/2.5.0/sassc-2.0.0
cd libsass
make lib/libsass.so
mkdir lib
cc -Wall -O2 -I /usr/local/lib/libsass/include -fPIC -fPIC -c -o src/cencode.o src/cencode.c
src/cencode.c: In function ‘base64_encode_block’:
src/cencode.c:50:5: warning: empty declaration
     __attribute__ ((fallthrough));
     ^
src/cencode.c:64:5: warning: empty declaration
     __attribute__ ((fallthrough));
     ^
g++ -Wall -O2 -std=c++0x -I /usr/local/lib/libsass/include -fPIC -fPIC -c -o src/ast.o src/ast.cpp
g++ -Wall -O2 -std=c++0x -I /usr/local/lib/libsass/include -fPIC -fPIC -c -o src/node.o src/node.cpp
g++ -Wall -O2 -std=c++0x -I /usr/local/lib/libsass/include -fPIC -fPIC -c -o src/context.o src/context.cpp
g++ -Wall -O2 -std=c++0x -I /usr/local/lib/libsass/include -fPIC -fPIC -c -o src/constants.o src/constants.cpp
g++ -Wall -O2 -std=c++0x -I /usr/local/lib/libsass/include -fPIC -fPIC -c -o src/functions.o src/functions.cpp
g++ -Wall -O2 -std=c++0x -I /usr/local/lib/libsass/include -fPIC -fPIC -c -o src/color_maps.o src/color_maps.cpp
g++ -Wall -O2 -std=c++0x -I /usr/local/lib/libsass/include -fPIC -fPIC -c -o src/environment.o src/environment.cpp
g++ -Wall -O2 -std=c++0x -I /usr/local/lib/libsass/include -fPIC -fPIC -c -o src/ast_fwd_decl.o src/ast_fwd_decl.cpp
g++ -Wall -O2 -std=c++0x -I /usr/local/lib/libsass/include -fPIC -fPIC -c -o src/bind.o src/bind.cpp
g++ -Wall -O2 -std=c++0x -I /usr/local/lib/libsass/include -fPIC -fPIC -c -o src/file.o src/file.cpp
g++ -Wall -O2 -std=c++0x -I /usr/local/lib/libsass/include -fPIC -fPIC -c -o src/util.o src/util.cpp
g++ -Wall -O2 -std=c++0x -I /usr/local/lib/libsass/include -fPIC -fPIC -c -o src/json.o src/json.cpp
g++ -Wall -O2 -std=c++0x -I /usr/local/lib/libsass/include -fPIC -fPIC -c -o src/units.o src/units.cpp
g++ -Wall -O2 -std=c++0x -I /usr/local/lib/libsass/include -fPIC -fPIC -c -o src/values.o src/values.cpp
src/values.cpp: In function ‘Sass_Value* Sass::ast_node_to_sass_value(Sass::Expression_Ptr)’:
src/values.cpp:25:91: error: too many arguments to function ‘Sass_Value* sass_make_list(size_t, Sass_Separator)’
       union Sass_Value* list = sass_make_list(l->size(), l->separator(), l->is_bracketed());
                                                                                           ^
In file included from /usr/local/lib/libsass/include/sass.h:9:0,
                 from src/values.cpp:2:
/usr/local/lib/libsass/include/sass/values.h:53:34: note: declared here
 ADDAPI union Sass_Value* ADDCALL sass_make_list    (size_t len, enum Sass_Separator sep);
                                  ^
src/values.cpp: In function ‘Sass::Value* Sass::sass_value_to_ast_node(const Sass_Value*)’:
src/values.cpp:104:55: error: ‘sass_list_get_is_bracketed’ was not declared in this scope
         l->is_bracketed(sass_list_get_is_bracketed(val));
                                                       ^
Makefile:249: recipe for target 'src/values.o' failed
make: *** [src/values.o] Error 1
rake aborted!
Command failed with status (2): [make lib/libsass.so...]
/var/lib/gems/2.5.0/gems/sassc-2.0.0/lib/tasks/libsass.rb:31:in `block (2 levels) in <top (required)>'
/var/lib/gems/2.5.0/gems/sassc-2.0.0/lib/tasks/libsass.rb:13:in `block (3 levels) in <top (required)>'
/var/lib/gems/2.5.0/gems/sassc-2.0.0/lib/tasks/libsass.rb:12:in `block (2 levels) in <top (required)>'
/var/lib/gems/2.5.0/gems/rake-12.3.2/exe/rake:27:in `<main>'
Tasks: TOP => lib/libsass.so
(See full trace by running task with --trace)

rake failed, exit code 1

Gem files will remain installed in /var/lib/gems/2.5.0/gems/sassc-2.0.0 for inspection.
Results logged to /var/lib/gems/2.5.0/extensions/x86_64-linux/2.5.0/sassc-2.0.0/gem_make.out
`

**Comment by azeroual2017** [comment]
Hello,
I have the same error, have you resolved it ? 

THKS

**Comment by nschonni** [comment]
Think this is probably an issue for https://github.com/sass/sassc-ruby rather than here
