### ISSUE TITLE
On Windows search for libsass.so instead of libsass.dll

### ISSUE THREAD

**Issue by baibinja** [sass/sassc#259]
On Windows search for libsass.so instead of libsass.dll
I have installed new gem _sassc version 2.1.0_
_Window version 10_
and try to migrate db (rake db:migration) and have error:

```
LoadError: Could not open library 'C:/jruby-9.2.5.0/lib/ruby/gems/shared/gems/sassc-2.1.0/lib/sassc/libsass.so' : The operation completed successfully.
uri:classloader:/jruby/kernel/kernel.rb:13:in `require_relative'
uri:classloader:/jruby/kernel/kernel.rb:13:in `require_relative'
>Bundler.require(*Rails.groups)  
```                                                                                 

in the searched folder have file libsass.dll just need to search for it on Windows

hope on quick solution, thanks!

**Comment by baibinja** [comment]
I haven't got new sassc-ruby gem since june. But I have new sass-rails version 5.1.0. Maybe then it is sass-rails issue?

**Comment by baibinja** [comment]
https://github.com/sass/sassc-rails/issues/134
